"""Event types for agent execution tracking."""

from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Any, Dict, List, Optional
from enum import Enum
import uuid


class EventType(str, Enum):
    """Event type enumeration."""
    # Session lifecycle
    SESSION_START = "session_start"
    SESSION_END = "session_end"
    QUERY = "query"

    # Query lifecycle (legacy - kept for backward compatibility)
    START = "start"
    COMPLETE = "complete"

    # Agent events
    PLAN = "plan"
    MESSAGE = "message"
    PARTIAL_MESSAGE = "partial_message"
    TOOL_USE = "tool_use"
    TOOL_RESULT = "tool_result"
    PROGRESS = "progress"
    SYSTEM = "system"
    ERROR = "error"

    # Approval events
    APPROVAL_REQUEST = "approval_request"
    APPROVAL_RESPONSE = "approval_response"

    # Metrics events
    METRICS = "metrics"


@dataclass
class AgentEvent:
    """Base event class for all agent events."""

    type: EventType
    event_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    session_id: Optional[str] = None
    user_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert event to dictionary."""
        return asdict(self)

    def to_json(self) -> str:
        """Convert event to JSON string."""
        import json
        return json.dumps(self.to_dict())


@dataclass
class StartEvent(AgentEvent):
    """Emitted when agent execution starts."""

    type: EventType = EventType.START
    prompt: str = ""
    options: Dict[str, Any] = field(default_factory=dict)


@dataclass
class CompleteEvent(AgentEvent):
    """Emitted when agent execution completes."""

    type: EventType = EventType.COMPLETE
    duration_ms: int = 0
    total_cost_usd: Optional[float] = None
    num_turns: int = 0
    result: Optional[str] = None
    usage: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TaskInfo:
    """Individual task information."""
    content: str
    status: str  # "pending" | "in_progress" | "completed"
    active_form: str


@dataclass
class PlanChanges:
    """Changes in the plan."""
    added: List[str] = field(default_factory=list)
    removed: List[str] = field(default_factory=list)
    status_changed: List[Dict[str, str]] = field(default_factory=list)


@dataclass
class PlanEvent(AgentEvent):
    """Emitted when agent creates or updates task plan."""

    type: EventType = EventType.PLAN
    todos: List[TaskInfo] = field(default_factory=list)
    total_tasks: int = 0
    completed: int = 0
    in_progress: int = 0
    pending: int = 0
    changes: Optional[PlanChanges] = None
    tool_use_id: str = ""


@dataclass
class MessageEvent(AgentEvent):
    """Emitted for agent messages."""

    type: EventType = EventType.MESSAGE
    role: str = ""  # "assistant" | "user" | "system"
    content: str = ""
    model: Optional[str] = None
    thinking: Optional[str] = None


@dataclass
class PartialMessageEvent(AgentEvent):
    """Emitted for incremental text streaming (word-by-word).

    When include_partial_messages is enabled, this event streams
    text content incrementally as it's generated by the model.
    """

    type: EventType = EventType.PARTIAL_MESSAGE
    delta: str = ""
    index: int = 0
    content_type: str = "text"


@dataclass
class ToolUseEvent(AgentEvent):
    """Emitted when agent uses a tool."""

    type: EventType = EventType.TOOL_USE
    tool_name: str = ""
    tool_use_id: str = ""
    input: Dict[str, Any] = field(default_factory=dict)
    originated_from_message_id: Optional[str] = None  # Links to MessageEvent that announced this tool


@dataclass
class ToolResultEvent(AgentEvent):
    """Emitted when tool execution completes."""

    type: EventType = EventType.TOOL_RESULT
    tool_use_id: str = ""
    tool_name: str = ""
    output: Any = None
    is_error: bool = False
    originated_from_message_id: Optional[str] = None  # Links to MessageEvent that announced this tool


@dataclass
class ProgressEvent(AgentEvent):
    """Emitted for progress updates."""

    type: EventType = EventType.PROGRESS
    completed: int = 0
    total: int = 0
    percentage: float = 0.0
    current_task: Optional[str] = None


@dataclass
class SystemEvent(AgentEvent):
    """Emitted for system-level events."""

    type: EventType = EventType.SYSTEM
    subtype: str = ""
    data: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ErrorEvent(AgentEvent):
    """Emitted when an error occurs."""

    type: EventType = EventType.ERROR
    error: str = ""
    error_type: str = ""
    context: Dict[str, Any] = field(default_factory=dict)
    traceback: Optional[str] = None


@dataclass
class SessionStartEvent(AgentEvent):
    """Emitted when a new session is created."""

    type: EventType = EventType.SESSION_START
    tags: List[str] = field(default_factory=list)
    system_prompt: Optional[str] = None  # The full system prompt sent to Claude Agent SDK


@dataclass
class SessionEndEvent(AgentEvent):
    """Emitted when a session is closed."""

    type: EventType = EventType.SESSION_END
    total_queries: int = 0
    total_duration_ms: int = 0


@dataclass
class QueryEvent(AgentEvent):
    """Emitted when a new query is sent in a session."""

    type: EventType = EventType.QUERY
    prompt: str = ""
    query_number: int = 1


@dataclass
class ApprovalRequestEvent(AgentEvent):
    """Emitted when a tool requires user approval before execution."""

    type: EventType = EventType.APPROVAL_REQUEST
    tool_use_id: str = ""
    tool_name: str = ""
    tool_input: Dict[str, Any] = field(default_factory=dict)
    status: str = "pending"  # "pending" | "approved" | "rejected"
    risk_level: str = "medium"  # "safe" | "medium" | "high"


@dataclass
class ApprovalResponseEvent(AgentEvent):
    """Emitted when user approves or rejects a tool execution."""

    type: EventType = EventType.APPROVAL_RESPONSE
    tool_use_id: str = ""
    approved: bool = False
    remember: bool = False  # Remember approval for this tool in session
    reason: Optional[str] = None


@dataclass
class MetricsEvent(AgentEvent):
    """Emitted periodically during query execution to provide live metrics updates."""

    type: EventType = EventType.METRICS
    duration_ms: int = 0
    input_tokens: int = 0
    output_tokens: int = 0
    total_cost_usd: Optional[float] = None
